name: Package and release
# learn from https://github.com/tickbh/wmproxy/blob/main/.github/workflows/ci.yml
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  TZ: Asia/Shanghai
  TARGET_TAR: atomic-amd64-linux.tar

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug Info
        run: |
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
          echo "GITHUB_SHA: ${{ github.sha }}"
          echo "GITHUB_REPOSITORY: ${{ github.repository }}"
          echo "==========================="
          echo "secrets.AGITHUB_TOKEN: ${{ secrets.AGITHUB_TOKEN }}"
          echo "github.ref : ${{ github.ref }}"
          echo "github.ref_name: ${{github.ref_name}}"
          echo "---"
          echo "${{env.TARGET_TAR}}"

      - name: Generate SHA-256
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Release binary and SHA-256 checksum to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./${{env.TARGET_TAR}}
            ./${{env.TARGET_TAR}}.sha256